#DEPARTMENT-SERVICE
spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/microservice2
    username: root
    password:
  jpa:
    hibernate.ddl-auto: update
    generate-ddl: true
    show-sql: true
  application: 
    name: DEPARTMENT-SERVICE
  config:
    import: "optional:configserver:"
  zipkin:
    base-url: http://127.0.0.1:9411/
    
server:
  port: 9001
  